@startuml
title 基于GitHub的实验管理平台--删除评分点信息的顺序图
actor teachers
teachers -> details: 给出要删除的detail_id
details -> details_scores: 根据detail_id,删除details_scores中对应的实验评分点成绩数据
details -> details: 根据detail_id,删除details中数据


@enduml