@startuml
title 基于GitHub的实验管理平台--删除课程信息的顺序图
actor teachers
teachers -> experiments: 给出要删除的experiment_id
experiments -> details_scores: 根据experiment_id,删除details_scores中对应的实验评分点成绩数据
experiments -> experiments_scores: 根据experiment_id,删除experiments_scores中对应的实验成绩数据
experiments -> details: 根据experiment_id,删除details中数据
experiments -> experiments: 根据experiment_id,删除experiments中数据


@enduml