@startuml

package "图书管理系统类包" #DDDDDD {
  
	class 图书管理员 {
		__ private data __
		 	-String adminId
	     	-String name
	    	-boolean sex
	    	-Date born
	    	-byte[] photo
	 	-- encrypted --
	 	    -String password
		__ public method __
			+维护图书()
			+归还图书()
			+借还图书()
			+维护读者()
	}
	class 超级管理员 {
		__ private data __
		 	-String superAdminId
		    -String name
		    -boolean sex
		    -Date born
		    -byte[] photo
	 	-- encrypted --
	 		-String password
		__ public method __
	 		+维护图书管理员信息()

	}
	class 读者 {
	 	__ private data __
		 	-String readerId;
		    -String name;
		    -boolean sex;
		    -Date born;
		    -String spec;
		    -int num;
		    -byte[] photo;
	 	-- encrypted --
	 		-String password
		__ public method __
			+查询借阅信息()
			+预订图书()
			+取消预订()
		
	}

	class 图书 {
		__ private data __
		 	 -int bookId
		     -String ISBN
		     -String bookName
		     -String author
		     -String publisher
		     -float price
		     -int cnum
		     -int snum
		     -String summary
		     -byte[] photo
	}

	class 借书记录 {
		__ private data __
		 	-Integer id
		    -int bookId
		    -String readerId
		    -String ISBN
		    -Date ltime
		    -boolean lendConfirm
		    -boolean returnRequest
	}

	note  "<color:blue>省略Getter和Setter方法。</color>" as note1

	图书管理员 <|- 超级管理员 : 维护图书管理员信息
	图书管理员 "N" -- "N" 读者 : 维护读者信息
	读者 "1" -- "N" 借书记录 : 借书和还书
	借书记录 "1" -- "1" 图书 : 一一对应
	借书记录 "N" -- "1" 图书管理员 : 登记和归还
	图书管理员 "N" -- "N" 图书 : 维护图书


	

  
}


@enduml