@startuml

object 图书 {
		"书号" bookId = 1
		"ISBN号" ISBN = "978-986-181-729"
	 	"书名" bookName = "信息系统分析与设计"
	 	"作者" author = "王晓敏"
	 	"简介" summary = "信息系统分析与设计》是2004年西安电子科技大学出版社出版的图书,
	 					 作者是卫红春。主要讲述了信息系统的基本概念、基本理论和基本方法。"
	 	"出版社" publisher = "科学出版社"
	 	"价格" price = "10.1"
	 	"总量" cnum = "500"
	 	"库存" snum = "400"
		"封面" photo = "??WExif"
	}
	note  right : "sex为Boolean类型，1表示男，0表示女\n封面为字节型数组，直接存放在数据库中"
@enduml