@startuml
skinparam titleBorderRoundCorner 15
skinparam titleBorderThickness 2
skinparam titleBorderColor #Black
skinparam titleFontSize 24
Title 显示任教课程列表流程图


actor 老师主页面顶部菜单
actor API服务
database 数据库存储

== 老师主页面 ==
老师主页面顶部菜单->API服务:传入老师的teacher_id
API服务->API服务:判断teacher_id的合法性
API服务->数据库存储:访问courses表中是否有对应课程字段
数据库存储->API服务:返回课程course信息
API服务->老师主页面顶部菜单:返回所任教课程的列表信息
== 老师登录后正常使用，\n每次请求都会访问API==

@enduml